### ISSUE TITLE
切札3つチェック入れた状態で4/3選択された扱いになって登録できない事象

### ISSUE THREAD

**Issue by enuo-n** [kirisakku/FuruyoniDeckManager#24]
■事象概要
特定の操作を行うと、画面上では切札を３つ選択している状態にもかかわらず切札のカウントが4になり、正常にデッキ登録できない事象が発生。

■再現手順
1.ライラオリジンを選択した状態でライラの切札を3つチェック
2.ライラアナザーを選択
3.ライラの切札のチェックを全解除
　→1つ目を解除したとき3/3選択の表示。
　　チェックボックスの解除がカウントされてないように思われます。
　→全解除したとき、切札のカウントは1/3と表示
4.ライラオリジンを選択
5.切札を再度3枚選ぶ
6.切札のカウントが4/3と表示。デッキ登録がグレーアウトされ選択不可になった。

■補足事項
こちらではライラの他、ユキヒでも同様の手順にて事象を確認。
全部テストできてませんが、おそらく他メガミでも同様と思われます。

１．では雷螺風神爪、天雷召喚陣、風魔招来孔の順でチェック。
また他５パターン程度試しましたが同様に事象が発生。
チェック順に事象再現有無は関連しないものと考えています。
３．のチェックを外す順番も特に関係性はないように見受けられました。

**Comment by kirisakku** [comment]
対応完了したのでクローズ
