### ISSUE TITLE
ホノカアナザーの切札画像の誤り

### ISSUE THREAD

**Issue by enuo-n** [kirisakku/FuruyoniDeckManager#28]
■事象概要
ホノカアナザーの追加札「旧き虚路を歩みゆく」をタップすると「ひとり目覚めて」の画像が表示される。

■再現手順
1.メガミ選択画面でサリヤアナザー、ホノカアナザーを選択。
2.ホノカアナザー側の追加札ボタンをタップ。
3.「旧き虚路を歩みゆく」をタップ。
4.「ひとり目覚めて」の画像が表示される。

■補足事項
サリヤアナザーの他にも組み合わせを試し同様の事象を確認、特定の組み合わせに起因する事象ではないように考えられるため、単純に画像の紐づけの誤りかと考えられます。

影響度軽微(ホノカアナザーの使用率ェ…ホノカはそこにいますか？)

**Comment by kirisakku** [comment]
既に修正済みです。最新版アプリを取得してください
